packages:
  - apps/*
  - packages/*
catalog:
  "@amap/amap-jsapi-loader": ^1.0.1
  "@commitlint/cli": ^17.8.1
  "@commitlint/config-conventional": ^17.8.1
  "@element-plus/icons-vue": ^2.3.1
  "@eslint/js": ^9.13.0
  "@liaoliaots/nestjs-redis": ^9.0.5
  "@nestjs/axios": ^3.0.2
  "@nestjs/bull": ^11.0.2
  "@nestjs/cli": ^10.4.2
  "@nestjs/common": ^10.3.10
  "@nestjs/config": ^3.2.3
  "@nestjs/core": ^10.3.10
  "@nestjs/jwt": ^10.2.0
  "@nestjs/mapped-types": ^2.0.5
  "@nestjs/passport": ^10.0.3
  "@nestjs/platform-express": ^10.3.10
  "@nestjs/schedule": ^4.1.1
  "@nestjs/schematics": ^10.1.2
  "@nestjs/serve-static": ^4.0.2
  "@nestjs/swagger": ^7.4.0
  "@nestjs/testing": ^10.3.10
  "@nestjs/typeorm": ^10.0.2
  "@rollup/plugin-commonjs": ^28.0.6
  "@rollup/plugin-json": ^6.1.0
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-typescript": ^12.1.3
  "@types/express": ^4.17.21
  "@types/file-saver": ^2.0.7
  "@types/jest": ^29.5.12
  "@types/lodash": ^4.17.6
  "@types/lodash-es": ^4.17.12
  "@types/multer": ^1.4.11
  "@types/nodemailer": ^6.4.17
  "@types/nprogress": ^0.2.3
  "@types/passport-jwt": ^3.0.13
  "@types/passport-local": ^1.0.38
  "@types/request-ip": ^0.0.41
  "@types/sortablejs": ^1.15.8
  "@types/supertest": ^2.0.16
  "@types/uuid": ^10.0.0
  "@vitejs/plugin-vue": ^5.1.4
  "@vitejs/plugin-vue-jsx": ^4.0.1
  "@vueuse/core": ^10.11.1
  "@wangeditor/editor": ^5.1.23
  "@wangeditor/editor-for-vue": ^5.1.12
  axios: ^1.7.7
  bcryptjs: ^3.0.2
  bullmq: ^5.49.2
  class-transformer: ^0.5.1
  class-validator: ^0.14.1
  cos-nodejs-sdk-v5: ^2.14.3
  cron: 3.2.1
  cron-parser: ^5.1.1
  cross-env: ^7.0.3
  cz-git: ^1.8.0
  czg: ^1.8.0
  echarts: ^5.5.1
  element-plus: ^2.8.6
  eslint-config-prettier: ^9.1.0
  eslint-define-config: ^2.1.0
  eslint-plugin-vue: ^9.29.1
  exceljs: ^4.4.0
  express-rate-limit: ^7.3.1
  file-saver: ^2.0.5
  fuse.js: ^7.0.0
  helmet: ^7.1.0
  husky: ^8.0.3
  iconv-lite: ^0.6.3
  ioredis: ^5.4.1
  jest: ^29.7.0
  js-cookie: ^3.0.5
  js-yaml: ^4.1.0
  jsencrypt: ^3.3.2
  jszip: ^3.10.1
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  mitt: ^3.0.1
  moment: ^2.30.1
  mqtt: ^5.11.0
  multer: 1.4.5-lts.1
  mysql2: 3.6.5
  nest-winston: ^1.10.2
  node-disk-info: ^1.3.0
  nodemailer: ^6.9.16
  normalize.css: ^8.0.1
  nprogress: ^0.2.0
  passport: ^0.7.0
  passport-jwt: ^4.0.1
  passport-local: ^1.0.0
  path-to-regexp: ^7.0.0
  pinia: ^2.2.4
  pinia-plugin-persistedstate: ^3.2.3
  qiniu: ^7.12.0
  reflect-metadata: ^0.1.14
  request-ip: ^3.3.0
  rimraf: ^6.0.1
  rollup: ^4.44.1
  rollup-plugin-dts: ^6.2.1
  rollup-plugin-terser: ^7.0.2
  rxjs: ^7.8.1
  sass: 1.79.0
  sortablejs: ^1.15.3
  source-map-support: ^0.5.21
  supertest: ^6.3.4
  svg-captcha: ^1.4.0
  swagger-ui-express: ^5.0.1
  terser: ^5.36.0
  ts-jest: ^29.2.2
  ts-loader: ^9.5.1
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tslib: ^2.8.1
  typeorm: ^0.3.20
  unocss: ^0.61.9
  unplugin-auto-import: ^0.17.8
  unplugin-vue-components: ^0.27.4
  useragent: ^2.3.0
  uuid: ^10.0.0
  vite: ^5.4.9
  vite-plugin-compression: ^0.5.1
  vite-plugin-imagemin: ^0.6.1
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-progress: ^0.0.7
  vite-plugin-restart: ^0.4.1
  vite-plugin-svg-icons: ^2.0.1
  vite-plugin-vue-devtools: ^7.5.2
  vue: ^3.5.12
  vue-cropper: ^1.1.4
  vue-eslint-parser: ^9.4.3
  vue-router: ^4.4.5
  vue-tsc: ^2.1.6
  vxe-pc-ui: 4.2.26
  vxe-table: ^4.7.94
  winston: ^3.17.0
  winston-daily-rotate-file: ^5.0.0
