# 开发环境配置
app:
  prefix: ''
  port: 6060
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关
  file:
    # 是否为本地文件服务或cos
    isLocal: true
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: '../upload'
    # 文件服务器地址，这是开发环境的配置 生产环境请自行配置成可访问域名
    domain: 'http://localhost:6060'
    # 文件虚拟路径, 必须以 / 开头， 如 http://localhost:8081/static/****.jpg  , 如果不需要则 设置 ''
    serveRoot: '/upload'
    # 文件大小限制，单位M
    maxSize: 10
# 腾讯云cos配置
cos:
  secretId: 'LnBGTt5m6fy4JyleKCeYCh1Hhgh_tuSAN7kiLi4X'
  secretKey: 'TizLfssZ0aAhpGX_PM1r8wlnCgaTjgh1CBpiD9Sq'
  bucket: 'cz6-hw'
  region: ''
  domain: 'http://qiniu.cz6hy9.top'
  location: ''
# 数据库配置
db:
  mysql:
    host: '43.139.39.151'
    username: 'test1'
    password: '123456'
    database: 'test1'
    port: 3306
    charset: 'utf8mb4'
    logger: 'file'
    logging: true
    multipleStatements: true
    dropSchema: false
    # 根据实体自动创建数据库表， 生产环境建议关闭
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true

# redis 配置
redis:
  host: '43.139.39.151'
  password: '123456'
  port: 6379
  db: 1
  keyPrefix: ''

# jwt 配置
jwt:
  secretkey: 'you_secretkey'
  expiresin: '1h'
  refreshExpiresIn: '2h'
# 权限 白名单配置
perm:
  router:
    whitelist:
      [
        { path: '/captchaImage', method: 'GET' },
        { path: '/register', method: 'POST' },
        { path: '/login', method: 'POST' },
        { path: '/logout', method: 'POST' },
        { path: '/common/area/list', method: 'GET' },
        { path: '/system/config/refreshCache', method: 'Delete' },
        # { path: '/system/user/:userId', method: 'GET' },
      ]

# 用户相关
# 初始密码， 重置密码
user:
  initialPassword: '123456'
