/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    FormView: typeof import('./../src/components/FormView/index.vue')['default']
    Grid: typeof import('./../src/components/Grid/index.vue')['default']
    GridItem: typeof import('./../src/components/Grid/components/GridItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../src/components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./../src/components/SearchForm/components/SearchFormItem.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TableColumn: typeof import('./../src/components/TableView/components/TableColumn.vue')['default']
    TableFooter: typeof import('./../src/components/TableView/components/TableFooter.vue')['default']
    TableHeader: typeof import('./../src/components/TableView/components/TableHeader.vue')['default']
    TableView: typeof import('./../src/components/TableView/index.vue')['default']
    UploadImg: typeof import('./../src/components/Upload/UploadImg.vue')['default']
    UploadImgs: typeof import('./../src/components/Upload/UploadImgs.vue')['default']
    WangEditor: typeof import('./../src/components/WangEditor/index.vue')['default']
  }
}
